### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by rayangou** [appknox/ember-pace#1]
When I run ember build in windows platform, I get the below error.

ember build --prod
- Building
Environment: production
cleaning up...
Build Error (Funnel)

ENOENT: no such file or directory, open '\\?\C:\Users\username\AppData\Local\Temp\broccoli-2553607oAEmaVyGFv\out-166-funnel_ember_pace_theme_funnel\app\styles\themes\blue\pace-theme-minimal.css'

**Comment by rayangou** [comment]
ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, lstat 'C:\Users\username\path_to_app/C:\Users\username\path_to_app\node_modules\pace-progressbar\themes\blue\pace-theme-minimal.css'
    at Object.lstatSync (fs.js:924:3)
    at symlinkWindows (C:\Users\username\path_to_app\node_modules\symlink-or-copy\index.js:154:25)
    at symlinkOrCopySync (C:\Users\username\path_to_app\node_modules\symlink-or-copy\index.js:99:5)
    at Object.handleFs (C:\Users\username\path_to_app\node_modules\broccoli-funnel\node_modules\broccoli-output-wrapper\dist\index.js:40:24)
    at Funnel._copy (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:500:19)
    at Funnel.processFile (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:484:10)
    at Funnel._applyPatch (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:398:14)
    at Funnel.<anonymous> (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:352:12)
    at Array.forEach (<anonymous>)
    at Funnel.processFilters (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:351:13)
  - code: [undefined]
  - codeFrame: ENOENT: no such file or directory, lstat 'C:\Users\username\path_to_app/C:\Users\username\path_to_app\node_modules\pace-progressbar\themes\blue\pace-theme-minimal.css'
  - errorMessage: ENOENT: no such file or directory, lstat 'C:\Users\username\path_to_app/C:\Users\username\path_to_app\node_modules\pace-progressbar\themes\blue\pace-theme-minimal.css'
        at Funnel (EmberPaceThemeFunnel)
-~- created here: -~-
    at new Plugin (C:\Users\username\path_to_app\node_modules\broccoli-funnel\node_modules\broccoli-plugin\dist\index.js:45:33)
    at new Funnel (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:62:5)
    at new funnel (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:517:10)
    at Class.treeForAddonStyles (C:\Users\username\path_to_app\node_modules\@appknox\ember-pace\index.js:49:33)
    at Class.superWrapper [as treeForAddonStyles] (C:\Users\username\path_to_app\node_modules\core-object\lib\assign-properties.js:34:20)
    at Class._treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:700:33)
    at Class.treeForAddon (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:944:46)
    at Class._treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:700:33)
    at Class.treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:660:21)
    at C:\Users\username\path_to_app\node_modules\ember-cli\lib\broccoli\ember-app.js:721:26
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: ENOENT: no such file or directory, lstat 'C:\Users\username\path_to_app/C:\Users\username\path_to_app\node_modules\pace-progressbar\themes\blue\pace-theme-minimal.css'
        at Funnel (EmberPaceThemeFunnel)
-~- created here: -~-
    at new Plugin (C:\Users\username\path_to_app\node_modules\broccoli-funnel\node_modules\broccoli-plugin\dist\index.js:45:33)
    at new Funnel (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:62:5)
    at new funnel (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:517:10)
    at Class.treeForAddonStyles (C:\Users\username\path_to_app\node_modules\@appknox\ember-pace\index.js:49:33)
    at Class.superWrapper [as treeForAddonStyles] (C:\Users\username\path_to_app\node_modules\core-object\lib\assign-properties.js:34:20)
    at Class._treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:700:33)
    at Class.treeForAddon (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:944:46)
    at Class._treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:700:33)
    at Class.treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:660:21)
    at C:\Users\username\path_to_app\node_modules\ember-cli\lib\broccoli\ember-app.js:721:26
-~- (end) -~-
  - name: Error
  - nodeAnnotation: EmberPaceThemeFunnel
  - nodeName: Funnel
  - originalErrorMessage: ENOENT: no such file or directory, lstat 'C:\Users\username\path_to_app/C:\Users\username\path_to_app\node_modules\pace-progressbar\themes\blue\pace-theme-minimal.css'
  - stack: Error: ENOENT: no such file or directory, lstat 'C:\Users\username\path_to_app/C:\Users\username\path_to_app\node_modules\pace-progressbar\themes\blue\pace-theme-minimal.css'
    at Object.lstatSync (fs.js:924:3)
    at symlinkWindows (C:\Users\username\path_to_app\node_modules\symlink-or-copy\index.js:154:25)
    at symlinkOrCopySync (C:\Users\username\path_to_app\node_modules\symlink-or-copy\index.js:99:5)
    at Object.handleFs (C:\Users\username\path_to_app\node_modules\broccoli-funnel\node_modules\broccoli-output-wrapper\dist\index.js:40:24)
    at Funnel._copy (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:500:19)
    at Funnel.processFile (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:484:10)
    at Funnel._applyPatch (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:398:14)
    at Funnel.<anonymous> (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:352:12)
    at Array.forEach (<anonymous>)
    at Funnel.processFilters (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:351:13)

**Comment by rayangou** [comment]
ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, open '\\?\C:\Users\username\AppData\Local\Temp\broccoli-4704srjkApjfGB8E\out-166-funnel_ember_pace_theme_funnel\app\styles\themes\blue\pace-theme-minimal.css'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1279:35)
    at symlinkWindows (C:\Users\username\path_to_app\node_modules\symlink-or-copy\index.js:177:18)
    at symlinkOrCopySync (C:\Users\username\path_to_app\node_modules\symlink-or-copy\index.js:99:5)
    at Object.handleFs (C:\Users\username\path_to_app\node_modules\broccoli-funnel\node_modules\broccoli-output-wrapper\dist\index.js:40:24)
    at Funnel._copy (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:500:19)
    at Funnel.processFile (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:484:10)
    at Funnel._applyPatch (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:398:14)
    at Funnel.<anonymous> (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:352:12)
    at Array.forEach (<anonymous>)
  - code: [undefined]
  - codeFrame: ENOENT: no such file or directory, open '\\?\C:\Users\username\AppData\Local\Temp\broccoli-4704srjkApjfGB8E\out-166-funnel_ember_pace_theme_funnel\app\styles\themes\blue\pace-theme-minimal.css'
  - errorMessage: ENOENT: no such file or directory, open '\\?\C:\Users\username\AppData\Local\Temp\broccoli-4704srjkApjfGB8E\out-166-funnel_ember_pace_theme_funnel\app\styles\themes\blue\pace-theme-minimal.css'
        at Funnel (EmberPaceThemeFunnel)
-~- created here: -~-
    at new Plugin (C:\Users\username\path_to_app\node_modules\broccoli-funnel\node_modules\broccoli-plugin\dist\index.js:45:33)
    at new Funnel (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:62:5)
    at new funnel (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:517:10)
    at Class.treeForAddonStyles (C:\Users\username\path_to_app\node_modules\@appknox\ember-pace\index.js:49:33)
    at Class.superWrapper [as treeForAddonStyles] (C:\Users\username\path_to_app\node_modules\core-object\lib\assign-properties.js:34:20)
    at Class._treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:700:33)
    at Class.treeForAddon (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:944:46)
    at Class._treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:700:33)
    at Class.treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:660:21)
    at C:\Users\username\path_to_app\node_modules\ember-cli\lib\broccoli\ember-app.js:721:26
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: ENOENT: no such file or directory, open '\\?\C:\Users\username\AppData\Local\Temp\broccoli-4704srjkApjfGB8E\out-166-funnel_ember_pace_theme_funnel\app\styles\themes\blue\pace-theme-minimal.css'
        at Funnel (EmberPaceThemeFunnel)
-~- created here: -~-
    at new Plugin (C:\Users\username\path_to_app\node_modules\broccoli-funnel\node_modules\broccoli-plugin\dist\index.js:45:33)
    at new Funnel (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:62:5)
    at new funnel (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:517:10)
    at Class.treeForAddonStyles (C:\Users\username\path_to_app\node_modules\@appknox\ember-pace\index.js:49:33)
    at Class.superWrapper [as treeForAddonStyles] (C:\Users\username\path_to_app\node_modules\core-object\lib\assign-properties.js:34:20)
    at Class._treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:700:33)
    at Class.treeForAddon (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:944:46)
    at Class._treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:700:33)
    at Class.treeFor (C:\Users\username\path_to_app\node_modules\ember-cli\lib\models\addon.js:660:21)
    at C:\Users\username\path_to_app\node_modules\ember-cli\lib\broccoli\ember-app.js:721:26
-~- (end) -~-
  - name: Error
  - nodeAnnotation: EmberPaceThemeFunnel
  - nodeName: Funnel
  - originalErrorMessage: ENOENT: no such file or directory, open '\\?\C:\Users\username\AppData\Local\Temp\broccoli-4704srjkApjfGB8E\out-166-funnel_ember_pace_theme_funnel\app\styles\themes\blue\pace-theme-minimal.css'
  - stack: Error: ENOENT: no such file or directory, open '\\?\C:\Users\username\AppData\Local\Temp\broccoli-4704srjkApjfGB8E\out-166-funnel_ember_pace_theme_funnel\app\styles\themes\blue\pace-theme-minimal.css'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1279:35)
    at symlinkWindows (C:\Users\username\path_to_app\node_modules\symlink-or-copy\index.js:177:18)
    at symlinkOrCopySync (C:\Users\username\path_to_app\node_modules\symlink-or-copy\index.js:99:5)
    at Object.handleFs (C:\Users\username\path_to_app\node_modules\broccoli-funnel\node_modules\broccoli-output-wrapper\dist\index.js:40:24)
    at Funnel._copy (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:500:19)
    at Funnel.processFile (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:484:10)
    at Funnel._applyPatch (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:398:14)
    at Funnel.<anonymous> (C:\Users\username\path_to_app\node_modules\broccoli-funnel\index.js:352:12)
    at Array.forEach (<anonymous>)
